2025-05-13 17:33:17,607 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8158' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'mariana.cardoso', 'departamento': 'RH', 'endereco_ip': '10.0.101.224', 'mac_adress': 'D0:94:66:B1:1E:97', 'hostname': '4WJ5VW2', 'memoria_ram': 8, 'ssd': 240, 'ramal': 8158, 'anydesk': 1410054294, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 33, 17, 600290), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 33, 17, 600299)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:34:19,854 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8027' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'miqueias.gomes', 'departamento': 'Tesouraria', 'endereco_ip': '10.0.225.19', 'mac_adress': '8A:7B:EB:E8:6C:6B', 'hostname': 'F02MHJ2', 'memoria_ram': 8, 'ssd': 222, 'ramal': 8027, 'anydesk': 404548940, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 34, 19, 848157), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 34, 19, 848166)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:34:23,167 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8027' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'miqueias.gomes', 'departamento': 'Tesouraria', 'endereco_ip': '10.0.225.19', 'mac_adress': '8A:7B:EB:E8:6C:6B', 'hostname': 'F02MHJ2', 'memoria_ram': 8, 'ssd': 222, 'ramal': 8027, 'anydesk': 404548940, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 34, 23, 161474), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 34, 23, 161483)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:34:29,780 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8027' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'miqueias.gomes', 'departamento': 'Tesouraria', 'endereco_ip': '10.0.225.19', 'mac_adress': '8A:7B:EB:E8:6C:6B', 'hostname': 'F02MHJ2', 'memoria_ram': 8, 'ssd': 222, 'ramal': 8027, 'anydesk': 404548940, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 34, 29, 773594), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 34, 29, 773603)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:36:44,899 INFO: Nova máquina cadastrada: josefa.santana (10.0.225.39) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:37:03,803 INFO: Nova máquina cadastrada: gustavo.lima (10.0.225.30) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:40:31,124 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8149' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'izadora.franzon', 'departamento': 'Corec', 'endereco_ip': '10.0.225.94', 'mac_adress': '84:7B:EB:F9:8D:0D', 'hostname': 'F09LHJ2', 'memoria_ram': 8, 'ssd': 237, 'ramal': 8149, 'anydesk': 1064683631, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 40, 31, 117638), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 40, 31, 117647)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:40:39,230 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8149' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'izadora.franzon', 'departamento': 'Corec', 'endereco_ip': '10.0.225.94', 'mac_adress': '84:7B:EB:F9:8D:0D', 'hostname': 'F09LHJ2', 'memoria_ram': 8, 'ssd': 237, 'ramal': 8149, 'anydesk': 1064683631, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 40, 39, 223563), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 40, 39, 223572)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:42:32,603 INFO: Nova máquina cadastrada: andrea.bueno (10.0.225.16) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:43:22,311 INFO: Nova máquina cadastrada: edison.silva (10.0.225.28) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:46:01,345 INFO: Nova máquina cadastrada: luiz.felipe (10.0.254.240) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:47:03,734 INFO: Nova máquina cadastrada: jeannette.ferreira (10.0.225.26) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:49:03,222 INFO: Nova máquina cadastrada: thiago.lima (10.0.225.22) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:51:12,604 INFO: Nova máquina cadastrada: helena.ribeiro (10.0.226.56) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:52:36,316 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8146' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'alexandro.gomes', 'departamento': 'Fiscal', 'endereco_ip': '10.0.225.23', 'mac_adress': 'F8:B1:56:FC:40:19', 'hostname': 'JDDCG22', 'memoria_ram': 6, 'ssd': 240, 'ramal': 8146, 'anydesk': 1771823137, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 52, 36, 310510), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 52, 36, 310519)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:52:44,574 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8146' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'alexandro.gomes', 'departamento': 'Fiscal', 'endereco_ip': '10.0.225.23', 'mac_adress': 'F8:B1:56:FC:40:19', 'hostname': 'JDDCG22', 'memoria_ram': 6, 'ssd': 240, 'ramal': 8146, 'anydesk': 1771823137, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 52, 44, 567598), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 52, 44, 567607)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:55:22,068 INFO: Nova máquina cadastrada: oderlei.fabiano (10.0.227.5) [in /var/www/Portal-TI-Manager/app.py:301]
2025-05-13 17:56:43,439 ERROR: Erro ao cadastrar máquina: (pymysql.err.IntegrityError) (1062, "Duplicate entry '8146' for key 'registros.ix_registros_ramal'")
[SQL: INSERT INTO registros (base, nome, departamento, endereco_ip, mac_adress, hostname, memoria_ram, ssd, ramal, anydesk, data_cadastro, ultima_atualizacao) VALUES (%(base)s, %(nome)s, %(departamento)s, %(endereco_ip)s, %(mac_adress)s, %(hostname)s, %(memoria_ram)s, %(ssd)s, %(ramal)s, %(anydesk)s, %(data_cadastro)s, %(ultima_atualizacao)s)]
[parameters: {'base': 'SP', 'nome': 'maykon.gabriel', 'departamento': 'Copag', 'endereco_ip': '10.0.225.206', 'mac_adress': 'D0:94:66:B0:1B:27', 'hostname': '40Z54W2', 'memoria_ram': 8, 'ssd': 256, 'ramal': 8146, 'anydesk': 1541656676, 'data_cadastro': datetime.datetime(2025, 5, 13, 17, 56, 43, 432836), 'ultima_atualizacao': datetime.datetime(2025, 5, 13, 17, 56, 43, 432845)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /var/www/Portal-TI-Manager/app.py:305]
2025-05-13 17:58:44,611 INFO: Nova máquina cadastrada: danielli.batista (10.0.226.132) [in /var/www/Portal-TI-Manager/app.py:301]
